  title: "吴龙淼" 
  header-img: "img/twitter.jpg"
  tagline: "cn"  
  description: "欢迎访问我的博客，一起学习进步！"
  baseurl: ""
  url: "http://www.daoshangfei.top" 
  paginate: 5
#全局配置
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
include:
safe:
#全站范围的默认值
defaults:
  -
    scope: 
      path: "" #代表项目所有的文件
      type: "posts" #只给类型是posts的文件设置默认布局（pages posts drafts）
    values:
      layout: "post"
      author: "吴龙淼" 
      header-img: "img/zhihu.jpg" 

# 网站地址小图标
gavatar: "img/favicon.png"
favicon: "img/favicon.png"
#社交软件用户名
github_username: wulongmiao
#输出
timezone: "Asia/fujian"

